[Appearance]
color_scheme_path=/usr/share/qt5ct/colors/arc.conf
custom_palette=false
icon_theme=Papirus-Dark
standard_dialogs=gtk2
style=GTK+

[Fonts]
fixed=@Variant(\0\0\0\x10\0\x34\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\x12)
general=@Variant(\0\0\0\x10\0\x34\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\x12)